% This script was used to generate new data from the original dataset (X)
% which is consists of 50 spectrum measures of benign samples and 50 
% spectrum measures of malignant samples. Note that the variable space (S)
% of X contains 462 variables which corresponds to the absorption readings 
% of a sample from 1800 cm^-1 to 850 cm^-1 at 4 cm^-1 resolution.
% 
% New spectrum samples were generated by first obtaining M<<462 number of 
% eigenvectors (V) for each classes which constitutes 99.99% of the class 
% data's variability. After obtaining the eigenvectors, X was then 
% projected to this lower-dimension space (S'). Lastly, new samples were 
% generated by randomly selecting a point (P') in S' within the line  
% connecting two randomly selected samples in S'. To translate the new 
% sample (P') from S' to S, P' was projected back to S using V (see 
% "getData.m").
%
% Note that this code can be used to generate new samples provided that a
% spectral dataset for malignant (X_mal.mat) and benign (X_ben.mat) samples 
% are provided. Needless to say, the original dataset is not present due to
% patenting issues. However, you may still use this code by using
% "getData.m" to generate your own dataset!

clc; 
clear all;

%% loading original dataset

% These lines were used to load the original dataset. 
load("X_mal.mat");
load("X_ben.mat");

n_mal = size(X_mal,1);
n_ben = size(X_ben,1);

%% dataset preprocessing

% eigenparameter computations for benign samples.
S = X_ben'*X_ben;
[V_ben, D_ben] = eig(S);
D_ben = diag(D_ben)/sum(D_ben,'all');

% sum(D_ben(end-5:end)); % uncomment to use.
% line 15 is used to check how many eigenvectors is needed to consider at
% least 99.99% of the sample variation among benign samples. In the
% original dataset, it takes 6 eigenvectors to satisfy the said condition.

V_ben = V_ben(:,end-5:end); 
save("V_ben","V_ben");
PCA_ben = X_ben*V_ben; % projecting the benign samples from S to S'

% eigenparameter computations for malignant samples.
S = X_mal'*X_mal;
[V_mal, D_mal] = eig(S);
D_mal = diag(D_mal)/sum(D_mal,'all');

% sum(D_mal(end-4:end)); % uncomment to use.
% line 52 is used to check how many eigenvectors is needed to consider at
% least 99.99% of the sample variation among malignant samples. In the
% original dataset, it takes 5 eigenvectors to satisfy the said condition.

V_mal = V_mal(:,end-4:end);
save("V_mal","V_mal");
PCA_mal = X_mal*V_mal; % projecting the malignant samples from S to S'

%% generation of new data

N = 5000; % number of samples to be generated per class.

% generation of benign samples in the PCA space.
n = randi(n_ben,N,2); % randomizing N pairs in S' belonging to the benign class.
r = rand(N,1); % randomizing the point between each pair in which the new data will be generated in S'.
PCA_ben_gen = (PCA_ben(n(:,2),:) - PCA_ben(n(:,1),:)).*r + PCA_ben(n(:,1),:);
save("PCA_ben_gen","PCA_ben_gen");

% generation of malignant samples in the PCA space.
n = randi(n_mal,N,2); % randomizing N pairs in S' belonging to the malignant class.
r = rand(N,1); % randomizing the point between each pair in which the new data will be generated in S'.
PCA_mal_gen = (PCA_mal(n(:,2),:) - PCA_mal(n(:,1),:)).*r + PCA_mal(n(:,1),:);
save("PCA_mal_gen","PCA_mal_gen");

